plugins {
    id "org.springframework.boot" version "4.0.1"
    id "io.spring.dependency-management" version "1.1.7"
    id "org.openapi.generator" version "7.17.0"
    id "java"
}

group = "ru.otus.demo"
version = "0.0.1"
description = "demo-api"

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
    genCompile.extendsFrom compile
}

repositories {
    mavenCentral()
}

def lombokMapstructBindingVersion = "0.2.0"
def mapStructVersion = "1.6.3"
def springBootVersion = "4.0.1"
def springdocOpenapiStarterVersion = "3.0.0"

dependencies {

    implementation("org.springdoc:springdoc-openapi-starter-common:${springdocOpenapiStarterVersion}")
    implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:${springdocOpenapiStarterVersion}")

    implementation("org.springframework.boot:spring-boot-h2console")
    implementation("org.springframework.boot:spring-boot-jackson2")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
    implementation("org.springframework.boot:spring-boot-starter-liquibase")
    implementation("org.springframework.boot:spring-boot-starter-web")

    runtimeOnly("com.h2database:h2")
    runtimeOnly("org.postgresql:postgresql")

    compileOnly("org.mapstruct:mapstruct:${mapStructVersion}")
    compileOnly("org.projectlombok:lombok")
    compileOnly("org.openapitools:jackson-databind-nullable:0.2.8")

    annotationProcessor("org.mapstruct:mapstruct-processor:${mapStructVersion}")
    annotationProcessor("org.projectlombok:lombok-mapstruct-binding:${lombokMapstructBindingVersion}")
    annotationProcessor("org.projectlombok:lombok")

    testImplementation("org.springframework.boot:spring-boot-starter-data-jpa-test")
    testImplementation("org.springframework.boot:spring-boot-starter-liquibase-test")
    testImplementation("org.springframework.boot:spring-boot-starter-webmvc-test")
    testImplementation("com.h2database:h2")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:${springBootVersion}"
    }
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()

    testLogging {
        events("passed", "skipped", "failed")
    }
}

sourceSets {
    main {
        java {
            srcDir "src/main/java"
            srcDir "build/src/main/java"
        }
    }
}

openApiGenerate {
    ext.sourcesDir = "build/src/main/java"
    generatorName = "spring"
    inputSpec = "${rootDir}/src/main/resources/open-api/item-api.yml"
    outputDir = "${buildDir}"
    apiPackage = "ru.otus.demo.controllers"
    invokerPackage = "ru.otus.demo"
    modelPackage = "ru.otus.demo.dtos"
    openapiGeneratorIgnoreList = ["**/ApiUtil.java"]
    configOptions = [
        dateLibrary: "java8",
        additionalModelTypeAnnotations: "@lombok.Data;@lombok.Builder;@lombok.NoArgsConstructor;@lombok.AllArgsConstructor",
        interfaceOnly: "true",
        skipDefaultInterface: "true",
        generatePom: "false",
        useJakartaEe: "true"
    ]
}

compileJava.dependsOn "openApiGenerate"